### ISSUE TITLE
window not defined error when web workers are used.

### ISSUE THREAD

**Issue by saisandeepvaddi** [esetnik/customize-cra-react-refresh#5] opened 2020-02-11 23:21 UTC
![image](https://user-images.githubusercontent.com/13838175/74288469-7499e880-4cfa-11ea-9419-7548fad3dadc.png)

Tried setting `output.globalObject: this` and `output.globalObject: self`. But, no luck.

I am using [workerize-loader](https://github.com/developit/workerize-loader) for workers.

**Comment by esetnik** [comment] 2020-02-12 00:45
I’m not to familiar with workerize-loader so my ability to help may be limited. Can you share a minimal reproducible example project or code pen?

I found this https://github.com/developit/workerize-loader/issues/35#issuecomment-431504106 which may be relevant.

**Comment by saisandeepvaddi** [comment] 2020-02-13 02:41
I added a repo [https://github.com/saisandeepvaddi/customize-cra-react-refresh-issue](https://github.com/saisandeepvaddi/customize-cra-react-refresh-issue) which could be used to reproduce issue.

I've already tried setting ` config.output.globalObject= self` which did not work.

But, when I remove `customize-cra-react-refresh` and switch back to HMR with [https://github.com/cdharris/react-app-rewire-hot-loader](https://github.com/cdharris/react-app-rewire-hot-loader) I don't see issue.

**Comment by esetnik** [comment] 2020-02-13 02:57
Thank you for the reproduction. I did some research and it appears this issue is actually caused by the underlying react-refresh-webpack-plugin. See https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/24 for more information.

**Comment by esetnik** [comment] 2020-02-13 03:01
A solution is actively being worked on at https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/29

**Comment by esetnik** [comment] 2020-03-11 19:32
@saisandeepvaddi can you confirm this has been fixed by upgrading to `@pmmmwh/react-fresh-webpack-plugin@0.2.0`

**Comment by saisandeepvaddi** [comment] 2020-03-16 19:25
@esetnik Yes, it fixes it. 

But `v0.2.0` broke other stuff with `webpack-hot-middleware`. [https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/45](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/45) which crashes CRA.

So, might wanna mention that issue and let users know to install `webpack-hot-middleware` as an additional dep in README.

Can I send a PR with updated package.json and README.md?

**Comment by saisandeepvaddi** [comment] 2020-03-16 19:38
Sent PR [https://github.com/esetnik/customize-cra-react-refresh/pull/9](https://github.com/esetnik/customize-cra-react-refresh/pull/9). Please let me know that's ok.

**Comment by esetnik** [comment] 2020-05-27 19:21
Please try v1.0.4 and if it solves your issue you can close this.

**Comment by esetnik** [comment] 2020-09-28 15:53
Hi @saisandeepvaddi since I haven't heard back from you i'm going to close this. Please let me know if you have any other issues.

**Closed as completed by esetnik** 2020-09-28 15:53 UTC
